version: '3'

services:

  mysql:
    image: mysql:5.5
    networks:
      - tasknet
    volumes:
      - mysqldata:/var/lib/mysql
      - mysqlconfig:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=task
    ports:
      - "3306:3306"

  fanni-app:
    build: .
    networks:
      - tasknet
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_PASS=123456
    ports:
      - "3000:3000"

networks:
  tasknet:

volumes:
  mysqldata:
    driver: local
  mysqlconfig:
    driver: local